sudo: false

language: node_js
node_js:
- "node"

matrix:
  include:
    - os: linux
      dist: bionic
    - os: osx

before_install:
- if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi
- npm install -g typescript

install:
- npm install
- npm run compile
- npm run vscode:prepublish
- npm install -g vsce
- vsce package
- ls -ll *vsix

script:
- npm run tslint
- npm test --silent
