name: Build on Push

on: [push]

jobs:
  test:
    name: Test on ${{ matrix.node-version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        node-version: [8.x, 10.x, 12.x]
        
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm install -g typescript tslint vsce
        npm install
        npm run compile
        npm run vscode:prepublish
        vsce package
        npm run tslint
        npm test
      env:
        CI: true
