name: Node.js CI

on: pull_request

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    name: Build on Ubuntu
    env:
      DISPLAY: ":99.0"
      CI: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        name: Start Xvfb
      - name: Install Podman
        id: install-gvproxy
        run: sudo apt install gvproxy
      - name: Install GVPROXY
        id: install-podman
        run: brew install podman
      - name: Initialize Podman Machine
        id: initialize-podman-machine
        run: podman machine init
      - name: Start Podman Machine
        id: start-podman-machine
        run: podman machine start
      - name: Install LanguageTool
        id: install-languagetool
        run: brew install languagetool
      - run: npm install -g typescript vsce json
      - run: npm ci
      - run: npm run vscode:prepublish
      - run: npm run test-compile
      - run: npm test
        name: Test
      - run: npm run lint
        name: ESLint

  macos-build:
    runs-on: macos-latest
    name: Build on MacOS
    env:
      CI: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install Podman
        id: install-podman
        run: brew install podman
      - name: Initialize Podman Machine
        id: initialize-podman-machine
        run: podman machine init
      - name: Start Podman Machine
        id: start-podman-machine
        run: podman machine start
      - name: Install LanguageTool
        id: install-languagetool
        run: brew install languagetool
      - run: npm install -g typescript vsce json
      - run: npm ci
      - run: npm run vscode:prepublish
      - run: npm run test-compile
      - run: npm test
        name: Test
      - run: npm run lint
        name: ESLint

  windows-build:
    runs-on: windows-latest
    name: Build on Windows
    env:
      CI: true
    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install Scoop
        id: install-scoop
        run: irm get.scoop.sh | iex
      - name: Install Podman
        id: install-podman
        run: scoop install podman
      - name: Initialize Podman Machine
        id: initialize-podman-machine
        run: podman machine init
      - name: Start Podman Machine
        id: start-podman-machine
        run: podman machine start
      - name: Install LanguageTool
        id: install-languagetool
        run: choco install languagetool
      - run: npm install -g typescript vsce json
      - run: npm ci
      - run: npm run vscode:prepublish
      - run: npm run test-compile
      - run: npm test
        name: Test
      - run: npm run lint
        name: ESLint
