name: Node.js CI - Push

on: push

jobs:
  # call-workflow-build-ubuntu:
  #   uses: ./.github/worklows/build-ubuntu.yml
  ubuntu-build:
    runs-on: ubuntu-22.04
    name: Build on Ubuntu
    env:
      DISPLAY: ":99.0"
      CI: true
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: "npm"
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Cache Homebrew
        id: cache-homebrew
        uses: actions/cache@v3
        with:
          path: /home/runner/.cache/Homebrew
          key: ${{ runner.os }}-homebrew
      # - name: Install Stuff
      #   id: install-stuff
      #   run: |
      #     sudo apt-get install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
      #     sudo /etc/init.d/dbus start &> /dev/null
      - name: Start Xvfb
        id: start-xvfb
        run: |
          /usr/bin/Xvfb :99 -screen 0 1024x768x24 +extension GLX +render -noreset >> $HOME/xsession.log 2>&1 &
      - name: Enable Linger for Podman
        id: enable-linger
        run: |
          loginctl enable-linger $(whoami)
          sleep 1
      - name: Set XDG_RUNTIME_DIR
        id: set-xdg_runtime_dir
        run: |
          echo "XDG_RUNTIME_DIR=/run/user/$UID" >> $GITHUB_ENV
          echo "DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/$UID/bus" >> $GITHUB_ENV
      - name: Install Podman, and Languagetool
        id: install-brew-podman
        run: |
          sudo apt-get purge podman buildah
          brew install podman languagetool
          sudo brew services restart podman
      - name: Start LanguageTool
        id: install-languagetool
        run: |
          echo "LTLINTER_MANAGED_CLASSPATH=/home/linuxbrew/.linuxbrew/opt/languagetool/libexec/languagetool-server.jar" >> $GITHUB_ENV
          echo "LTLINTER_TEST_SERVICES=true" >> $GITHUB_ENV
          brew services list
          curl -L http://localhost:8081/
      - name: Pre-warm Podman Service
        id: pull-languagetool-image
        run: |
          podman version
          podman pull docker.io/erikvl87/languagetool:5.8
          podman run -d -p 8082:8010 --name languagetool-test erikvl87/languagetool:5.9
          podman run -d -p 8081:8010 --name languagetool-external erikvl87/languagetool:5.9
          state=$(podman inspect languagetool-test|jq -r '.[0].State.Status')
          while [ $state != "running" ]; do
            echo "State: $state"
            sleep 5
            state=$(podman inspect languagetool-test|jq -r '.[0].State.Status')
          done;
      - run: npm install -g typescript vsce json
      - run: npm ci
      - run: npm run vscode:prepublish
      - run: npm run test-compile
      - name: Test
        run: |
          npm test
      - name: ESLint
        run: npm run lint
