name: Node.js CI - Push

on: push

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    name: Build on Ubuntu
    env:
      DISPLAY: ":99.0"
      CI: true
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - name: Start Xvfb
        id: start-xvfb
        run: /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
      - name: Install Podman
        id: install-podman
        run: |
          sudo apt-get -y update
          sudo apt-get -y install podman
      - name: Install LanguageTool
        id: install-languagetool
        run: |
          curl --silent --location https://languagetool.org/download/LanguageTool-5.8.zip --output ~/LanguageTool-5.8.zip
          unzip ~/LanguageTool-5.8.zip -d ~/
      - name: Run LanguageTool
        id: run-languagetool
        run: |
          ls ~/
      - run: npm install -g typescript vsce json
      - run: npm ci
      - run: npm run vscode:prepublish
      - run: npm run test-compile
      - run: npm test
        name: Test
      - run: npm run lint
        name: ESLint
